# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.support.ui import Select
import unittest


class TestAddNewContact(unittest.TestCase):
    def setUp(self):
        self.wd = webdriver.Firefox()
        self.wd.implicitly_wait(30)
    
    def test_add_new_contact(self):
        wd = self.wd
        wd.get("http://localhost/addressbook/index.php")
        wd.find_element_by_name("user").click()
        wd.find_element_by_name("user").clear()
        wd.find_element_by_name("user").send_keys("admin")
        wd.find_element_by_name("pass").clear()
        wd.find_element_by_name("pass").send_keys("secret")
        wd.find_element_by_xpath("//input[@value='Login']").click()
        wd.find_element_by_link_text("add new").click()
        wd.find_element_by_name("firstname").click()
        wd.find_element_by_name("firstname").clear()
        wd.find_element_by_name("firstname").send_keys("First test")
        wd.find_element_by_name("middlename").clear()
        wd.find_element_by_name("middlename").send_keys("Middle test")
        wd.find_element_by_name("lastname").clear()
        wd.find_element_by_name("lastname").send_keys("Last test")
        wd.find_element_by_name("nickname").clear()
        wd.find_element_by_name("nickname").send_keys("Nick test")
        wd.find_element_by_name("title").click()
        wd.find_element_by_name("title").clear()
        wd.find_element_by_name("title").send_keys("Title test")
        wd.find_element_by_name("company").clear()
        wd.find_element_by_name("company").send_keys("Company test")
        wd.find_element_by_name("address").clear()
        wd.find_element_by_name("address").send_keys("Address test")
        wd.find_element_by_name("home").clear()
        wd.find_element_by_name("home").send_keys("12345")
        wd.find_element_by_name("mobile").clear()
        wd.find_element_by_name("mobile").send_keys("67890")
        wd.find_element_by_name("work").clear()
        wd.find_element_by_name("work").send_keys("54321")
        wd.find_element_by_name("fax").clear()
        wd.find_element_by_name("fax").send_keys("09876")
        wd.find_element_by_name("email").clear()
        wd.find_element_by_name("email").send_keys("test@test.tu")
        wd.find_element_by_name("email2").clear()
        wd.find_element_by_name("email2").send_keys("test2@test.tu")
        wd.find_element_by_name("email3").clear()
        wd.find_element_by_name("email3").send_keys("test3@test.tu")
        wd.find_element_by_name("homepage").clear()
        wd.find_element_by_name("homepage").send_keys("www.test.tu")
        wd.find_element_by_name("bday").click()
        Select(wd.find_element_by_name("bday")).select_by_visible_text("15")
        wd.find_element_by_xpath("//option[@value='15']").click()
        wd.find_element_by_name("bmonth").click()
        Select(wd.find_element_by_name("bmonth")).select_by_visible_text("January")
        wd.find_element_by_xpath("//option[@value='January']").click()
        wd.find_element_by_name("byear").click()
        wd.find_element_by_name("byear").clear()
        wd.find_element_by_name("byear").send_keys("1990")
        wd.find_element_by_name("aday").click()
        Select(wd.find_element_by_name("aday")).select_by_visible_text("15")
        wd.find_element_by_xpath("(//option[@value='15'])[2]").click()
        wd.find_element_by_name("amonth").click()
        Select(wd.find_element_by_name("amonth")).select_by_visible_text("January")
        wd.find_element_by_xpath("(//option[@value='January'])[2]").click()
        wd.find_element_by_name("ayear").click()
        wd.find_element_by_name("ayear").clear()
        wd.find_element_by_name("ayear").send_keys("1990")
        wd.find_element_by_name("new_group").click()
        wd.find_element_by_xpath("//option[@value='[none]']").click()
        wd.find_element_by_name("address2").click()
        wd.find_element_by_name("address2").clear()
        wd.find_element_by_name("address2").send_keys("Address test")
        wd.find_element_by_name("phone2").clear()
        wd.find_element_by_name("phone2").send_keys("www.test.tu")
        wd.find_element_by_name("notes").clear()
        wd.find_element_by_name("notes").send_keys("Notes test")
        wd.find_element_by_xpath("(//input[@name='submit'])[2]").click()
        wd.find_element_by_link_text("home page").click()
        wd.find_element_by_link_text("Logout").click()
    
    def tearDown(self):
        self.wd.quit()


if __name__ == "__main__":
    unittest.main()
